services:
  app:
    build: .
    container_name: spring_boot_app1
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hosting1
      SPRING_DATASOURCE_USERNAME: user1         # Matches POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: password1     # Matches POSTGRES_PASSWORD
    networks:
      - hosting1_network

  db:
    image: postgres:14
    container_name: hosting1_postgres_db
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=hosting1
    ports:
       - "5433:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    networks:
      - hosting1_network

networks:
  hosting1_network:

volumes:
  postgres_data1:
