name: Build, Push Docker Image, and Redeploy on Render

on:
  push:
    branches:
      - main  # Adjust this to your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t samuelgbenga/hostingdocker-app:latest .

      - name: Push the Docker image
        run: docker push samuelgbenga/hostingdocker-app:latest

      - name: Trigger Redeployment on Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
